# Generated by Django 2.2.10 on 2020-02-11 18:08

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'users',
                'abstract': False,
                'verbose_name': 'user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField()),
                ('etage', models.SmallIntegerField()),
                ('label', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('R', 'Ready'), ('D', 'Dirty'), ('C', 'Cleanup')], max_length=1)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_bleu.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('N', 'New'), ('C', 'Confirmed'), ('A', 'Arrived'), ('C', 'CheckedOut')], max_length=1)),
                ('receipt', models.FilePathField(max_length=250, path='/home/pluto/tmp', recursive=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', related_query_name='reservation', to='hotel_bleu.Room')),
            ],
        ),
    ]
